### ISSUE TITLE
Registracija ir prisijungimas naudojant Steam

### ISSUE THREAD

**Issue by SkepticalHippo** [SkepticalHippo/maze#101]

**Comment by SnoutUp** [comment]
Norėjau siūlyt Facebook login'ą. Paskutiniu metu labai pamėgau website'us, kuriuose galima užsiregistruot keliais mygtuko paspaudimais (daug registruotis tenka). Twitteris geriausiai būna, nes iš karto yra username/nickname sistema, bet LT nelabai kas jį naudoja.
