### ISSUE TITLE
Sekamos kategorijos

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#103]
IMHO, pagal nutylėjimą nerodymas tokių kategorijų kaip "Žaidimų kūrimas" (nesu objektyvus čia), jas tiesiog nužudo. Dabar nelabai yra prasmės ten kažką rašyti, nes paprasčiausiai niekas nepamatys :) 

Manyčiau ir programavimo kategorija ir grafikos visos subkategorijos galėtų/turėtų būti pažymėtos by default, o po to jau žmonės išsirankios,jeigu norės... Nes problema yra tame, kad dauguma naujų vartotojų gali niekad ir nesužinot, kad yra "žaidimo kūrimo" skyrius, kuris skamba įdomiau, nei "programavimas", bet yra subkategorija = nematomas.

**Comment by PovilasLT** [comment]
Jau sakyta kiek kartų - forumas skirtas žaidėjams, ne developeriams. Tad ir šios kategorijos nepasirinktos.

**Comment by SnoutUp** [comment]
Supratau, ačiū, kad nepasivarginai "pasakyt dar kartą". Auditorijos ieškosiu kitur.

**Comment by Bebrazmogis** [comment]
Hmm na dabar kai jau galima keisti individualiai, gal ir reikėtų default nustatyti viską(na gal išskyrus reklamas)

**Comment by Yiin-** [comment]
Na tiesą pasakius, žaidimų kūrimo temos ir yra labiau skirtos būtent žaidėjams, kad jie galėtų pratestuoti naujus bei kuriamus žaidimus, o ne developeriams, nes nėra klausinėjamą su programavimu susiijusių klausimų. Apsvarstytim įdėją pridėti "Kuriami žaidimai" kategoriją, kuri būtų matoma by default.

**Comment by SkepticalHippo** [comment]
Nėra tobulas tas mūsų sąrašas default kategorijų. Kai sudarinėjau, labai griežtai žiūrėjau į viską. Anyway, good point. Pridėta :)
