### ISSUE TITLE
Temos tipas "Pranešimas" - naudoti gali betkas

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#106]
Kaip supratau, temos tipą "Pranešimas" turi naudoti tik admins. Bent [čia](http://beta.maze.lt/zinynas#temu-tipai) taip parašyta.  Tai manau reikėtų nerodyti to tipo sąraše usreiams.

**Comment by PovilasLT** [comment]
@Bebrazmogis  -  Neleidžia paprastiem nariam pasirinkt.

**Comment by Bebrazmogis** [comment]
Aaa. Tada čia ne klaida :)
