### ISSUE TITLE
Pridedant daug tarpų pranešimo rašymo box'e jis išsiplečia ANT pranešimų.

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#108]
http://i.imgur.com/wDwDvD2.png

Tiesiog pradėkit rašyt ir palaikykit ENTER.

**Comment by PovilasLT** [comment]
![](http://i.imgur.com/wDwDvD2.png)
(tiesiog pridėjau ft, kad nereiktų mygt ant linko :D)

į temą - čia su placeholderiu naujuoju tikriausiai susiję bus. Taip pat jei tema ilga, editorius prikimba viršuje vidury temos.

**Comment by SkepticalHippo** [comment]
@PovilasLT visiškai teisus. Dėl prikimbančio reply box'o čia.

**Comment by PovilasLT** [comment]
o kartais negalima būtų padaryt min-height ir overflow hidden? Čia mano durna galva tiek išmastė tik @SkepticalHippo ;D

**Comment by SkepticalHippo** [comment]
Užtenka tiesiog pakeisti height elemento, nes pirma per mažą uždėjęs buvau. Šiandien pakeisiu :)
