### ISSUE TITLE
Globaliai prisegtas temas rodyti nesvarbu ar subforumas pasirinktas

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#113]
jei nepasirinkta skiltis, nerodo tos temos globaliai prisegtos. Vistiek prisegtos temos turi svarbumą, tad jas būtų geriau rodyt nesvarbu ar pasirinkta ar ne.

**Comment by Yiin-** [comment]
nuu gaal, man asmeniškai vienodai tikrai, rodys jas ar ne, reiktų kitų nuomonės, nes aš nedaryčiau vien todėl kad kodint tingiu dalyką, kurio nenaudočiau pats niekad.

**Comment by Rinkuns** [comment]
Pagal mane vien žodis "globaliai" turėtų reikšti, kad ta tema turėtų būti matoma visų, nesvarbu ar pasirinkta skiltis ar ne. Tai aš visai už.

**Comment by Bebrazmogis** [comment]
Šitą pastebėjau ir aš. Tik nelabai suprantu ar globaliai prisegta tema šiuo metu skiriasi kažkuo nuo tiesiog prisegtos. Manau turėtų būti rodoma visur, galbūt NE prie "naujausiųi".

**Comment by Bebrazmogis** [comment]
https://github.com/SkepticalHippo/maze/blob/88c4c57f1cd5b54f334afc312b0691df3d1fc1fd/app/Topic.php#L75

Niekada neiškviesta.

**Comment by SkepticalHippo** [comment]
Bendra skiltis yra tiesiog "rinkinys" visų temų. Ten postinti negalima ir lokaliai prisegtos temos nėra aktualios bendram rinkiniui dažniausiai. Lokalūs prisegimai labiausiai skiriami skilties taisyklėms ir panašiems dalykams.

Jei daryti kažką panašaus, reiktų dar vieną temos prisegimo tipą daryti. Kitu atveju - irrelevant.
