### ISSUE TITLE
Pranešimų skaičiavimo funkcija pjauna grybą

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#114]
![](http://puu.sh/mxL8J/16e25e8aea.png)

Po vakar #111 fixo manau taip atsitiko. Rodo dviem postais mažiau nei iš tikro yra.

**Comment by Bebrazmogis** [comment]
Neaišku kodėl taip įvyko, kolkas sutvarkiau. Ar žinai kaip tai pakartoti? t.y. vėl padaryti kad būtų neigiamas skaičius?

**Comment by PovilasLT** [comment]
nop, tiesiog atsidaręs pamačiau. Dabar kaip ir viskas gerai.

**Comment by Bebrazmogis** [comment]
Hmm tai atsitinka ištrynus temą kuri TURI atsakymų.

**Comment by PovilasLT** [comment]
tuomet manau bus su #111 susiję

**Comment by Yiin-** [comment]
33b79a7d5f6dac579fbc20529c51660c04ba7de7
