### ISSUE TITLE
Atsakymo formos pozicija nepatogi atsakinėjimui į komentarus

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#12]
Norint atsakyti į naujausią temos komentarą reikia scrollinti į viršų. Norint atsakyti keliems žmonėms iš karto reikalai dar labiau komplikuojasi. 

Pasiūlymai: Inline (atsiranda paspaudus "reply") Fixed (pakimba viršuje(?) bescrollinant žemyn? Popout?

**Comment by SkepticalHippo** [comment]
d8b932eec3afaca4d5cf0a4fecd1509a27574e5d
