### ISSUE TITLE
prenumeratoriai

### ISSUE THREAD

**Issue by comaliot** [SkepticalHippo/maze#124]
nuėjus į nario profilį, kuris neturi prenumeratorių ir paspaudus "prenumeruoti" (būti pirmam prenumeratoriui) prie to nario statistikos "prenumeratoriai" rodo skaičių "2", nors turėtų rodyt "1".

**Comment by Bebrazmogis** [comment]
Confirmed, ne tik pirmam prenumeratoriui taip.
