### ISSUE TITLE
Iškelti temų tipus į duomenų bazę

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#125]
Tikriausiai kol kas dar galima palikti temos tipų specifiškumus hardcodintus bet patį temų sąrašą iškelt

**Comment by SkepticalHippo** [comment]
@Bebrazmogis būtų gerai padaryti per ateinantį savaitgalį. Man atrodo gali naudoti ankstesnį kodą. Nežinia kodėl praitą kartą išėmiau, bet @Yiin- berods sakė, kad viskas veikia.

**Comment by Bebrazmogis** [comment]
It's done, isn't it?

**Comment by SkepticalHippo** [comment]
@Bebrazmogis 👍
