### ISSUE TITLE
Minimalus markdown asmeninėse žinutėse

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#126]
Minimaliai manau reikėtų bent nuorodų ir paveikslėlių palaikymo, bet pilnas funkcionalumas irgi nepakenktų.

**Comment by PovilasLT** [comment]
tikrai už, reiktų pilno.

**Comment by Optimist78** [comment]
Priutariu! Aš už pilną

**Comment by Bebrazmogis** [comment]
Padaryta 71b673f27aa74ff3118c95aef69bc24ef340c0b2
