### ISSUE TITLE
Temos tipas "Klausimas" -  atsakymo pasirinkimas užrakinti ar ne?

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#128]
Anyway, temos tipas "Klausimas" veikia taip. Autorius gali pasirinkt atsakymą tinkamą temos. Tada tema užsirakina.

O jeigu adminas ją atrakins, tai į ją vėl galės rašyti bet neina keisti atsakymo. Tai ar manot kad adminai turėtų nebegalėti atrakint ar jeigu ją atrakino, tai autorius turėtų vėl galėti keisti atsakymą pasirinktą?

O gal apskritai nereikėtų jos užrakinti? Galbūt leisti tiek tęsti diskusijas, tiek pasirinkti kitą atsakymą. Stackoverflow.com pagrindu?

**Comment by PovilasLT** [comment]
paspaudus "Atsakymas" išmest popup su klausimu ar nori užrakinti temą

**Comment by Bebrazmogis** [comment]
[22:44:07] Justas - Bebras: Kai pasirenki "Atsakymas" tema užsirakina.
[22:44:11] vartotojas: Ai nu......
[22:44:15] vartotojas: Aš galvojau pacituoja


Manau popup bus vienas iš geriausių sprendimų.
