### ISSUE TITLE
Temų sąraše nėra jokios informacijos apie paskutinį atsakymą

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#13]
Trūksta paskutinio atsakymo autoriaus, jo ikonos (galbūt), datos (laiko "prieš"), tiesioginės nuorodos į jį.

**Comment by SkepticalHippo** [comment]
Su informacija apie paskutinį atsakymą yra labai sudėtinga situacija, bent kol bendruomenė nedidelė.

Pirmoje versijoje turėjom problemą, kur jei žmogus parašo po atsakymą į visas pagr. puslapio temas, visas pagrindinis puslapis būna nusėtas jo vardu ir avataru.

Klausimas atviras diskusijoms, tai jei yra kokių pasiųlymų tolimesnėms versijoms, galima diskutuoti čia :)

**Comment by SnoutUp** [comment]
Man tai, tiesą sakant, nelabai patinka tas avataras prie temos. Jis pagyvina puslapį, that's for sure, bet prideda painiavos ir neteisingai "informuoja". Nesakau, kad sena versija atrodė geriau, nes liūdnoki tie skrituliukai su skaičiais, bet ir negaliu pasiūlyt nieko geresnio.

Galbūt gerai atrodytų, jei apskritimai būtų spalvos pagal temos tipą (klausimas, diskusija, reklama(?), youtube video(!), twitch stream(!)) su ikonėle. Nebereikėtų to "diskusija" atkartot prie kiekvienos temos.

"Pranešimų", "peržiūrų", "parašyta", "auitorius" keisčiau į ikonas ir galbūt stumčiau dešinėn palikdamas antrą eilutę "Atsakė:" (ikona) Aurimas, prieš 5min. (aktyvi nuoroda į last reply).

Jei turėsiu laiko, tai pabandysiu pamaketuot, kad būtų aiškiau, bet kol kas bandau video naują įrašyt ir darbų turiu :)

**Comment by PovilasLT** [comment]
Bent prie dabartinės info pridėt Paskutinio pranešimo autorius: VartotojoVardas Paskutinio pranešimo data: 2016-01-06 15:05. Paspaudus ant datos nukeltų į patį pranešimą (atsižvelgiant į #32 SnoutUp komentarą), o paspaudus ant nicko į to čiūvo profilį

**Comment by SkepticalHippo** [comment]
Turėtų būti betoje testavimui gyvai. Apskritimai aplink avatarus labai baisiai atrodė :(
