### ISSUE TITLE
Pridėti margin iš šonų ant mobile prikibusio editoriaus

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#131]
kai per mobile prikimba editorius dingsta šone esantys tušti tarpeliai (gal 15px) ir labai pasistebi tas prikibimas. reiktų pridėt margin ar padding is šonų arba prikibusį kažkaip į containerį įmest

**Comment by SkepticalHippo** [comment]
Šiek tiek mažiau teksto tilptų tada. Ir taip vietos gana mažai mobiliuose prietaisuose, tai stengiamės vengti padding/margin (dvigubų) kur tai įmanoma.
