### ISSUE TITLE
Naujas temos tipas - Pamoka, Perku, Parduodu, ?Keičiu? Galerija? 

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#134]
Nauji temos tipai.

**Comment by Bebrazmogis** [comment]
Yiin padarys dar ir tipą "Galerija".

**Comment by Bebrazmogis** [comment]
Umm #177 prie to pačio.

**Comment by SkepticalHippo** [comment]
Pridėti du nauji temų tipai:

* Pamoka
* Paveikslėliai (Galerija)

Kiti temų tipai nepridėti, dėl ateinančios naujos platformos integracijos.
