### ISSUE TITLE
Neskaitytų temų atskyrimas nuo skaitytų

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#136]
Kokia forma tai pasireikš dar nenuspręsta, bet pradininkas šis pasiūlymas: https://maze.lt/tema/17038-forumo-skilciu-pasiulymas

**Comment by PovilasLT** [comment]
pastorint pavadinimą temos jei neskaityta?

**Comment by PovilasLT** [comment]
Idėja 1 - pavadinimas pastorintas listinge (700 font weight ant a elemento)
![](http://puu.sh/mR00t/be3f83cc65.png)

Idėja 2 - pilkesnis fonas ir pastorinimas
![](http://puu.sh/mR05v/dd01c4236b.png)

Idėja 3 - papildoma icona neskaitytoms temoms
![](http://i.imgur.com/7PmphVT.png)

Kol kas tiek, jei dar ką sugalvosiu papildysiu.

**Comment by SkepticalHippo** [comment]
Galima pridėti burbuliuką žalią, jei tema neskaityta. Panašiai, kaip buvo su vartotojų online/offline rodymu senoje versijoje. Rytoj pabandysiu sumaketuot kažką panašaus ir įdėsiu čia pažiūrėt :)

**Comment by PositiveGR** [comment]
Man labiausiai patiktų gal @PovilasLT 1 ir 2 variantas kartu. Ta prasme pastorinimas ir papilkinimas.

**Comment by SkepticalHippo** [comment]
#167
