### ISSUE TITLE
Pranešimų rašymo lauko pozicija

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#139]
Šiuo metu jis juda scrollinant būdamas ekrano viršuje.

https://maze.lt/tema/17404-komentaro-rasymo-laukelio-pozicija

**Comment by PovilasLT** [comment]
Dabar kai taip yra forumas išskirtinesnis atrodo, ir bent jau man patogiau kai viršuje laukelis. Aš nekeisčiau.

**Comment by Bebrazmogis** [comment]
Hmmm čia tikriausiai reikės balsuoti arba leisti pasirinkti. T.y padaryti abu variantus tiek apačioje tiek viršuje.

**Comment by PovilasLT** [comment]
1. Editorių pridėt ir po komentarais, ne tik virš.
2. Šone editoriaus padaryt mygtuką su [šita](https://fortawesome.github.io/Font-Awesome/icon/arrows-v) ikona. Ją paspaudus keistųsi editoriaus pozicija, arba bottom: 0 arba top: 0

**Comment by SkepticalHippo** [comment]
@PovilasLT sprendimas man atrodo geriausias šiuo atveju. Pažiūrėsiu dar #167 metu gal ką gudresnio sugalvosiu.
