### ISSUE TITLE
Skilčių navigacijos problemos

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#14]
* išskleisti submeniu susiskleidžia perkrovus puslapį
* neišskiriama aktyvi kategorija/subkategorija
* lankomos temos kategorija galėtų išsiskleisti automatiškai (skaitant temą Maze->Klaidos būtų patogiau patekti į Maze->Pasiūlymai be papildomų veiksmų)

**Comment by SkepticalHippo** [comment]
Trečias punktas įdėtas su 681e44cca1d3a50d7dd29a2fbd5070813d6db65a

**Comment by SnoutUp** [comment]
Kitas reikalas! Nežinau, kiek tai sudėtinga esamoj platformoj, bet būtų "tvarkingiau" be animacijos jį išskleist.

**Comment by SkepticalHippo** [comment]
Kol kas esamas kodas, atsakingas už išskleidimą/suskleidimą nelabai leidžia be animacijos ar be delay tą padaryti. Veliau pažiūrėsiu į kitas galimybes :)
