### ISSUE TITLE
Editorius prikimba per anksti jei yra paveikslėliai

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#146]
Jei yra paveikslėliai blogai apskaičiuojamas scroll aukštis nuo kurio reikia prikabint editorių viršui

https://maze.lt/tema/17466-platformos-atnaujinimas-maze-202 prikimba laiku
https://maze.lt/tema/17487-vasario-menesio-konkursas prikimba per anksti (dėl paveikslėlio)

**Comment by Bebrazmogis** [comment]
Prie to pačio, net nėra įprasto editoriaus: https://maze.lt/tema/17559-zaidimas-firewatch

**Comment by PovilasLT** [comment]
@Bebrazmogis - tame ir bėda, nes jis per anksti "prikimba", ir jo nebelieka savo vietoje.

**Comment by SkepticalHippo** [comment]
#167
