### ISSUE TITLE
"Tema prisegta globaliai"

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#148]
Rodyti tokias temas populiariausiuose nesvarbu, ar pasirinktas sub-forumas rodyti pagrindiniam, ar ne, kadangi taip išskirtos temos yra tikrai svarbios, ir jų praleist neturėtum nepasirinkęs tam tikro subforumo.

Neišskirti šių temų Naujausi sąraše.

**Comment by Yiin-** [comment]
fakin hard

**Comment by SkepticalHippo** [comment]
Tos temos yra svarbios "bendrame" konstekste. Anksčiau buvo jau aptarta, kad ne visos globaliai prisengtos temos yra aktualios lankytojams. Dėl to, turim du atskirus prisegimus - pagrindiniame puslapyje ir skiltyje.
