### ISSUE TITLE
Šoninė navigacija su affix

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#149]
Padaryt šoninę navigaciją su affix'u?

http://getbootstrap.com/javascript/#affix

**Comment by Bebrazmogis** [comment]
Šoninę navigaciją? Tai čia apie sub-forumus kalbi?

**Comment by PovilasLT** [comment]
Taip, nes jei ilgas postas, reik atgal scrollint

**Comment by SkepticalHippo** [comment]
Šoninė navigacija per ilga affixui. Kai pradės scrollinti affixas, nebus įmanoma pažiūrėti kas yra gale. Šoninis affixas veikia tik tais atvejais, kai labai nedaug turinio yra.
