### ISSUE TITLE
Nario profilis

### ISSUE THREAD

**Issue by Rinkuns** [SkepticalHippo/maze#15]
Paspaudus ant savo nuotraukas esu įmetamas į čia " http://beta.maze.lt/vartotojas/rin ", o tai reiškia, kad galiu save nusibausti (sounds wrong).

Bet paspaudus ant notifications ikonėlės esu įmetamas į čia " http://beta.maze.lt/profilis ", kur galiu keisti nustatymus.

Tiesiog keista, kad spaudžiant ant nuotraukos įmeta į "global view" if that makes sense.

**Comment by SkepticalHippo** [comment]
Tuos mygtukus */vartotojas* matome tik mes, tai didelės problemos kaip ir nėra.

Profilis ir vartotojo rodymas yra du atskiri puslapiai. Vartotojo puslapyje rodoma informacija apie vartotoją, profilyje rodoma viskas, kas aktualu tau pačiam.
