### ISSUE TITLE
 Skelbimų ir projektų reklamų rodymas

### ISSUE THREAD

**Issue by SkepticalHippo** [SkepticalHippo/maze#152]
Šiuo metu, pagal nutylėjimą (default), reklaminio/skelbimų pobūdžio temos nerodomos pagrindiniame puslapyje. Šitaip šiek tiek prarandama prasmė reklamuoti savo projektą maze puslapyje, nes pamato labai nedaug žmonių.

Mano pasiūlymas šiai problemai šiek tiek išspręsti būtų šitas temas rodyti dešinėje pusėje (visiškai nerodyti telefonų naudotojams). Tokiu atveju, temos nėra dėmesio centre, bet akys vis tiek užkibtų.

![maze_-_zaidimu_bendruomene___zaidimu_forumas___lietuviski_streamai](https://cloud.githubusercontent.com/assets/6921133/13161632/e4ff6458-d696-11e5-9945-cb1078c3efca.png)

**Comment by Yiin-** [comment]
Super idėja.
