### ISSUE TITLE
"View All rooms" tooltip nukirptas

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#156]
![image](https://cloud.githubusercontent.com/assets/11964308/13226413/f367ba80-d999-11e5-8d42-e13cc57c75a4.png)

**Comment by SkepticalHippo** [comment]
Nemanau, kad galim šitą pataisyt, nes čia `iframe` :( Vienintelis sprendimas off the top of my head, būtų perdaryt į savo chat'ą... Bet šitai būtų žiauriai nenaudinga, nes tada galėtume leisti chatinti tik tiems, kas yra prisijungę su savo twitch account'u prie maze :/
