### ISSUE TITLE
[Minor]Nuskandinus temą ji gauna pinned ikoną

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#158]
One may ask why does that happen...

https://github.com/SkepticalHippo/maze/blob/master/app/Http/Controllers/TopicsController.php#L269

https://github.com/SkepticalHippo/maze/blob/master/resources/views/topic/item.blade.php#L78

Aaand viskas kas ne nulis yra true!

**Comment by SkepticalHippo** [comment]
@Bebrazmogis good luck ;)
