### ISSUE TITLE
Un-sink-a-thread

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#159]
Temos nuskandinti galim, bet atskandinti ne :(

.... žinoma galima būtų ginčytis kad tai kas nuskandinta, prikelta negali būti. Paimkim Titaniką, vieną iš geriausiai žinomų nuskendusių objektų, ar jį galima iškelti į paviršių? Žinoma tai tikrai tai nėra neįmanoma, bet reikėtų itin daug pastangų, tikėtina kad pastangų kiekis nusvertų rezultatą. Bet grįžkime į maze, juk galime atskandinti temą su DB, tai atitiktų tas papildomas pastangas... 

Maze=titanikas.

**Comment by Yiin-** [comment]
...

**Comment by Yiin-** [comment]
66c6ab8347a62f0745c23b6224b630feabc1a924
