### ISSUE TITLE
Profilio nustatymai - socialiniai tinklai

### ISSUE THREAD

**Issue by Rinkuns** [SkepticalHippo/maze#16]
http://prntscr.com/9lww7d

Rašau bet ką metą tą patį.

Tas pats su youtube formatu.

Geriau padaryti tiesiog, kad įvedi savo id ir done, o ne įmesti full link arba padaryti, kad nemestų klaidos jei tik įvedi savo id.

**Comment by Bebrazmogis** [comment]
Yeah panašu kad tinka tik URL. Nelabai naudinga nebent kažką iš to URL gaus pats maze.

**Comment by Rinkuns** [comment]
Anyway toks mini tweak būtų gerai, nes nėra informacijos kas tinka ten, kas ne ir paskui žmonės pradės rašyti, kad išvis jiems neveikia nors reikia įkelti url, o ne id, kas man buvo >.>

**Comment by SkepticalHippo** [comment]
Geriau, manau, būtų prirašyti paaiškinimą nedidelį, kad Steam ir YouTube reikalingos nuorodos. Problema ta, kad, kiek pamenu, yra nemažai variantų galimų nuorodų, ir juos visus patikrinti užima nemažai laiko.
