### ISSUE TITLE
Forumo skilčių pasirinkimas

### ISSUE THREAD

**Issue by nerowalker** [SkepticalHippo/maze#166]
Siūlau pamygus ant skilčių pasirinkimo mygtuko išsiskleistų visos temos, taip paaiškėtų kam tas mygtukas. Čia iki tol, kol short presentation pasidarysit apie tai. :smile_cat: 

**EXTRA** Checklistus pakeisčiau į ikonas iš font awesome

-  _fa-check-circle-o_ [not selected]
-  _fa-check-circle_ [selected]

<img width="266" alt="screen shot 2016-02-23 at 16 19 30" src="https://cloud.githubusercontent.com/assets/12125314/13254294/6a37b49e-da49-11e5-8a4a-9986c1eb19d6.png">

<img width="289" alt="screen shot 2016-02-23 at 16 25 28" src="https://cloud.githubusercontent.com/assets/12125314/13254477/188e4b34-da4a-11e5-95d3-276024ce2f53.png">

**Comment by SkepticalHippo** [comment]
Not bad, įtraukiu į 2.1 versijos front-end pataisymų sąrašą :+1:
