### ISSUE TITLE
Front-End Pataisymai

### ISSUE THREAD

**Issue by SkepticalHippo** [SkepticalHippo/maze#167]
- [x] Struktūrizuoti front-end kodą.
- [x] Pradėti naudoti socketus prisijungusiems vartotojams.
- [x] Siųsti notifications per socketą.
- [x] Padaryti, kad paspaudus pranešimų "gaublį" pasirodytų burbuliukas, su neperžiūrėtais notifications. Panašiai kaip facebook.
- [x] Rodyti pranešimuose ir temose mažą ikonėlę, kada streameriai transliuoja (jei žmogus yra streameris).
- [ ] Pridėti "tutorialą" naujiems vartotojams.
- [ ] Rodyti skaitytas/neskaitytas temas.
- [ ] Rodyti naujų pranešimų kiekį temoje nuo paskutinio atidarymo.
- [x] Patobulinti privačių žinučių išvaizdą. Padaryti, kad būtų labiau panašu į pokalbių programėlę.
- [x] #166

**Comment by Bebrazmogis** [comment]
coool a checklist
