### ISSUE TITLE
Susisiekimo skilties klaida

### ISSUE THREAD

**Issue by nerowalker** [SkepticalHippo/maze#172]
[Pranešė čia](https://maze.lt/tema/17670-vartotojo-avataro-uzsidejimas-ir-informacija-susisiekti-skiltyje)
Kažkaip sulaužėt upload'ą, bet man bandat (šiuo atvėju pasikeisti) mano senas avataras nedingsta (thats cool). Tačiau kai redirectina į 404 avataro nėra.
<img width="1280" alt="screen shot 2016-02-24 at 09 04 19" src="https://cloud.githubusercontent.com/assets/12125314/13278021/a1ee1860-dad5-11e5-87c3-e13bcba0e5dc.png">

Pasitaisykit susisiekimo skiltyje esančius vardus. Spaudžiant ant pvz: 

Kaip yra:
- Edvinas -> keliauji į https://maze.lt/vartotojas/edvinas
- Yiin -> keliauji į https://maze.lt/vartotojas/yiin  
- etc...

Kaip reikia:
- Edvinas -> keliauji į https://maze.lt/vartotojas/skepticalhippo1
- Yiin -> keliauji į https://maze.lt/vartotojas/yiin4
- etc...

**Comment by Bebrazmogis** [comment]
4a15bdd0fe75320fdaab06e95af319f3552dc5fd
