### ISSUE TITLE
Apklausos

### ISSUE THREAD

**Issue by RonOfficial** [SkepticalHippo/maze#178]
Sveiki, pastebėjau, jog kartais kuriant temą, pasigendu vieno svarbaus bei naudingo įrankio, - apklausų sistemėlės, todėl siūlyčiau tokį dalyką šiame diskusijų forume. Manau tai tikrai reikalinga rašant pasiūlymus bei norint matyti bendruomenės balsų rezultatus, kadangi komentarai ne visuomet atitinka pagrindinį temoje esantį klausimą. Bendras įvaizdis galėtų būti paprastas laukelis su vienoje pusėje esančiu žaliu patinka (nykšcio į viršų) mygtuku kuris simbolizuotų teigiamą pasirinkimą - TAIP o kitoje pusėje esančiu raudonu nepatinka (nykšcio į apačią) mygtuku kuris simbolizuotų neigiamą pasirinkimą - NE. Bendras vaizdas turėtų būti panašus kaip Youtube vaizdo įrašų vertinimas.

**Comment by Bebrazmogis** [comment]
Bus padaryta, bet laaaabai negreitai(gal ~ 2.2), kadangi darbo labai daug palyginus su nauda.
