### ISSUE TITLE
Temos tipas kaip žymės?

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#179]
Paspaudus ant temos tipo, atidaryt visas naujausias to paties tipo temas būtų galima

**Comment by Bebrazmogis** [comment]
I like!! Bet gal reikėtų tai priskirti prie didesnio darbo, temų filtravimo?

**Comment by Bebrazmogis** [comment]
Nemanau kad bus padarytas prieš #125

**Comment by Bebrazmogis** [comment]
Hmm sub-forumuose kažkaip reikia mygtuko pašalinti tą filtrą...

Mastau per breadcrumbs.

Dabar yra taip:
URL: `http://maze.app/skiltis/viskas-ir-nieko?rodyti=populiariausi&tipas=3-konkursas`
Breadrumbs: `Pagrindinis / Viskas Ir nieko`

Siūlau
URL: `http://maze.app/skiltis/viskas-ir-nieko?rodyti=populiariausi&tipas=3-konkursas`
Breadrumbs: `Pagrindinis / Viskas Ir nieko / Konkursas`

**Comment by PovilasLT** [comment]
Maybe Konkursai tada? O ne Konkursas

**Comment by Bebrazmogis** [comment]
Hmm. Bet tai yra temos tipas, tema - vienaskaita. O filtravimas naudoja tipų pavadinimus, tai arba visur daugiskaita arba visur vienaskaita. Bet čia nebėda, dabar temų tipų pavadinimus galim pakeisti bet kada :)
