### ISSUE TITLE
MB versijoj neveikia skleidziamasis mygtukas 

### ISSUE THREAD

**Issue by codemenas** [SkepticalHippo/maze#18]
http://m.imgur.com/EVZkU3l
Šitas neveik

**Comment by PositiveGR** [comment]
Man irgi neveikia. Galvojau tik ant Windows Phone.

**Comment by Bebrazmogis** [comment]
Android su Google chrome irgi neveikia. Bet ir ant PC neveikia ;)

**Comment by SkepticalHippo** [comment]
Kol kas išimtas mobilios versijos navigacijos "išskleidimas".
