### ISSUE TITLE
Klaida su būsenos atnaujinimais profilio informacijoje

### ISSUE THREAD

**Issue by RonOfficial** [SkepticalHippo/maze#186]
Sveiki, pastebėjau šiokią tokia smulkią (turbūt) klaidelę su būsenos atnaujinimų fiksavimu profilio informacijos statistikoje. Norėjau ištrinti iš savo profilio visus būsenos atnaujinimus, tačiau vėliau pastebėjau, jog ištrynus būsenos atnaujinimus, - profilio informacijoje juos minusuoja, ir dabar rodo, jog esu parašęs -29 būsenos atnaujinimus. 
Tema: https://maze.lt/tema/17707-klaida-su-busenos-atnaujinimais-profilio-informacijoje

**Comment by Bebrazmogis** [comment]
Hmm man atkartoti to nepavyko. Galėtum detaliai papasakoti ką darei?

**Comment by ArvydasTorres** [comment]
Nuėjau į bet kurią temą kurioje esu parašęs pranešimą, paspaudžiu ant savo vartotojo vardo, pasirenku Būsenų atnaujinimai, ir ištrinu norimus būsenos atnaujinimus.

**Comment by Bebrazmogis** [comment]
@Yiin-  confirmed klaida?

@RonOfficial tavo būsenos atnaujinimų skaičiu sutaisiau. Patikrink ar pakartojus tai vis dar tampa neigiami :)
