### ISSUE TITLE
Pasiūlymas dėl temos tipų

### ISSUE THREAD

**Issue by ArvydasTorres** [SkepticalHippo/maze#188]
Sveiki, pastebėjau, jog temos tipai šiuo metu atlieka tik vieną pagrindinę funkciją - pažymi temas pagal pasirinktą temos tipą. Todėl siūlyčiau padaryti jog pagrindiniame puslapyje prie temos paspaudus ant temos tipo langelio (ikonos) - parodytų visas pasirinkto temos tipo temas.
Tema:  https://maze.lt/tema/17711-pasiulymas-del-temos-tipu

**Comment by Bebrazmogis** [comment]
#179
