### ISSUE TITLE
Manau reiktų daugiau spalvų.

### ISSUE THREAD

**Issue by PositiveGR** [SkepticalHippo/maze#19]
Tik pastebėjimas, bet tik įėjus į forumą man jis atrodo niūriai. Išdėstymas lyg ir viskas ok. Bet dizainas nelabai. Toks vienodas labai. Norisi daugiau spalvų arba paveiksliukų.

**Comment by SkepticalHippo** [comment]
Dizainas yra toks, koks yra dėl to, nes daugiausia dėmesio skiriama turiniui, o ne pačiai platformai ir "bells and whistles" :) Stengiamės per daug nekomplikuoti lankytojų sudėtingu dizainu.
