### ISSUE TITLE
Klaida su laiko atvaizdavimu

### ISSUE THREAD

**Issue by ArvydasTorres** [SkepticalHippo/maze#190]
Sveiki, pastebėjau tokį dalyką, jog ne visuomet forume laikas (kuris parodo prieš kiek laiko parašytas pranešimas) atvaizduojamas teisingai. Buvo tokių atvejų, jog parašiau pranešimą, maždaug po valandos grįžau į temą ir pastebėjau, jog rašo, kad pranešimas paašytas prieš 5 minutes, tačiau kas kartą laikas būna nurodytas skirtingai, bet kartais jis suveikia teisingai, ir rodo tikslų laiko atvaizdavimą.

**Comment by SkepticalHippo** [comment]
Ne į tą laiką žiūri tikriausiai. Visas laikas yra skaičiuojamas pagal serverio laikrodį.
