### ISSUE TITLE
Kur bus būsenos atnaujinimai?

### ISSUE THREAD

**Issue by PositiveGR** [SkepticalHippo/maze#20]
Kol kas nematau kažkokio sidebox'o kur būtų būsenos atnaujinimai, ar kažkas panašaus. Gal to iš vis nerodys pagrindiniame puslapyje?

**Comment by SkepticalHippo** [comment]
Nerodys. Viskas yra */profilis*

Pasirinkus "Visi" matysi visų žmonių būsenos atnaujinimus, o prie "Sekamieji" gali stebėti tik sekamus žmones.
