### ISSUE TITLE
Iskelti paminejimus, padaryti Mano/Sekamieji tabus

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#209]

**Comment by Bebrazmogis** [comment]
Dabar yra:

Sekamieji  |  Būsenų atnaujinimai
Visi  |  Paminėjimai  |  Temos |   Pranešimai   |  Būsenų atnaujinimai

Padaryti

Mano | Sekamieji | Paminėjimai | Būsenos atnaujinimai

Kur `Mano` ir `Sekamieji` tab'ai turės sub-tabus Visi |  Temos |   Pranešimai   |  Būsenų atnaujinimai

**Comment by SkepticalHippo** [comment]
@Bebrazmogis taip.
