### ISSUE TITLE
Pranešimo trinimas

### ISSUE THREAD

**Issue by Rinkuns** [SkepticalHippo/maze#21]
Ištrinant kažkieno kito pranešimo this happens (http://beta.maze.lt/home)
Ištrini savo pranešimą and this happens. 
Whoops, looks like something went wrong. http://beta.maze.lt/pranesimas/13080/istrinti

Edits so many edits.

**Comment by SkepticalHippo** [comment]
4313b85f78cf503f0b8dbd13bb9e9d59d795c011
