### ISSUE TITLE
Neveikia svetainė

### ISSUE THREAD

**Issue by Optimist78** [SkepticalHippo/maze#215]
![image](https://cloud.githubusercontent.com/assets/16598956/14966699/b9c68470-10ab-11e6-8dd7-8a1a1fd25fb3.png)

Viskas buvo gerai anksčiau, bet vat dabar taip rodo..

**Comment by Bebrazmogis** [comment]
Turėjom šiokių tokių nesklandumų. Dabar jau veikia! P.S. netgi atnaujinta ;)
