### ISSUE TITLE
https://www.maze.lt/ meta 404 klaidą

### ISSUE THREAD

**Issue by Yiin-** [SkepticalHippo/maze#216]
![http://i.imgur.com/eUCINJ3.png](http://i.imgur.com/eUCINJ3.png)

**Comment by Yiin-** [comment]
omg

**Comment by SkepticalHippo** [comment]
@Yiin- nesutaisyta šitas. Tiesiog won't fix, nes pirmas requestas kuris eina į www veikia gerai ir redirectinasi. Antrą requestą, jeigu jau esi maze.lt ir uždedi www priekyje, bando redirectinti pats laravel. Čia dėl wildcardų, nes wildcardinius subdomenus dėl tv.maze.lt handlina pats laravel.
