### ISSUE TITLE
Nauja tema neatsiranda naujose temose

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#22]
Sukurta tema: 
http://beta.maze.lt/tema/2397-ar-man-atrodo-ar-temos-neatsiranda-naujausiuose

Naujausiose nėra (koks nors filtras?): 
http://beta.maze.lt/?rodyti=naujausi

**Comment by SkepticalHippo** [comment]
Programavimo temos neatsiranda pagrindiniam puslapyje. Kai bus daugiau laiko, paskelbsių pilną sąrašą skilčių, kurios neatsiranda pagrindiniam puslapyje.

Planuose yra leisti individualiai pasirinkti skiltis, kurias nori matyti patys nariai :)
