### ISSUE TITLE
Ilgi komentarai nedalinami į eilutes

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#221]
Parašius ilgą komentarą be tarpų jis nesuskaidomas į kelias eilutes.

Žinoma joks protaujantis žmogus tokių komentarų nerašys, BET jeigu toks komentaras atsiranda, nusistumia valdymo ikonos į šoną ir neišeina jo redaguoti/trinti.

**Comment by SkepticalHippo** [comment]
Screenshot?

**Comment by Bebrazmogis** [comment]
Hmm panašu kad tai problema tik serverių komentaruose. Keista, nes viskas tas pats :/

**Comment by Bebrazmogis** [comment]
![screenshot from 2016-05-12 10 13 09](https://cloud.githubusercontent.com/assets/11964308/15206756/347e6e3c-182a-11e6-9627-0707269bfe07.png)


Nop. Locally tai bėda ir temose.

**Comment by SkepticalHippo** [comment]
Truksta CSS. Pranesimuose word-break uzdetas kad lauzytu zodzius i nauja
eilute bet kur.
