### ISSUE TITLE
Klaida naujos temos formoje

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#23]
Kursoriui esant "pavadinimo" laukelyje TAB klavišą reikia spausti DU kartus norint pereiti į "turinio" lauką. Norimas veikimas: kad reikėtų TAB spausti tik VIENĄ kartą. Nesinaudosiu, kol nebus pataisyta. 0/10. Chrome/Windows 7.

Sorry, nesusilaikiau :)

**Comment by SkepticalHippo** [comment]
Good point. Prie to paties, pridėsiu ir kad neblogai būtų klaviatūros shortcut padaryti temų postinimui.
