### ISSUE TITLE
Youtube (Twitch?) palaikymas 

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#25]
Naujoje versijoje neveikia automatinis youtube embedinimas. Gal būtų įdomu ir Twitch padaryt, jei nėra sudėtinga.

http://beta.maze.lt/tema/2398-o-kaip-su-youtube

**Comment by SkepticalHippo** [comment]
Jeigu naudoji RES (Reddit Enhancement Suite), tai norėčiau padaryti kažką panašaus. Kur paspaudi ant ikonėlės ir išsiskleidžia video. Esu jau kažką panašaus daręs, tai nebus labai sudėtinga manau :)

**Comment by SnoutUp** [comment]
Hm... Be ikonėlės būtų vienu paspaudimu mažiau. Ir, šiaip, gražiau :) Man visai patinka, kaip dabar yra maze.lt, tik proporcijos ten blogos ir "http://"  lieka kabėt.
