### ISSUE TITLE
Paieška again

### ISSUE THREAD

**Issue by Rinkuns** [SkepticalHippo/maze#27]
Pasirinkus pranešimų paiešką ir įrašius žodžius: lol arba lel išmeta error.

http://beta.maze.lt/paieska/rezultatai

**Comment by Bebrazmogis** [comment]
Kaip tu tai išvis atradai :D

**Comment by Rinkuns** [comment]
El macho man atrado. Nežinau kodėl jis ieškojo pranešimo su turiniu lol. Aš vėliau pabandžiau rašyti lel ir gavosi tas pats so yeah.
