### ISSUE TITLE
Norisi bent jau ryškesnių spalvų

### ISSUE THREAD

**Issue by PositiveGR** [SkepticalHippo/maze#30]
Kadangi dizainas nesikeis, tai gal galima bent jau pašviesinti tą žalią spalvą? Kad būtų kaip dabartiniame Maze.lt, nes labai niūriai atrodo ta tamsi...

**Comment by Bebrazmogis** [comment]
Dizaino klausimai nėra svarstomi. Jeigu ateityje nuspręsim daryti pakeitimų su išvaizda, bus paskelbta ir priimsim pasiūlymus.
