### ISSUE TITLE
Editoriaus klaidėlės

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#31]
Citatos tekstas ir antraštės tekstas neveikia (nepakeičia į jokį formatą)
![image](http://puu.sh/mkMGL/6b7b9a3004.png)
Taip pat (nežinau bugas ar nepadaryta) enter'is neduoda jokios prasmės - nenukelia į kitą eilutę, manau reikėtų tokios funkcijos

**Comment by PovilasLT** [comment]
taip pat - mobile nuscrollinus iki apačios editorius pradingsta nuo top, grįžus atgal į viršų ir scrollinant žemyn vėl nebeprisikabina.

**Comment by SkepticalHippo** [comment]
@Bebrazmogis related e05707ee01c1a946ca3eb7d7749771f3f3d2cf0e ?

**Comment by Bebrazmogis** [comment]
@SkepticalHippo turėjo būt related. Bet nesutaisė tas commit :/

**Comment by Bebrazmogis** [comment]
@PovilasLT citata ir heading sutaisyti. Dėl "enter", Edvinas kažkada pasakojo kažką apie tvarkingą rašymą. Jei nori pradėti naują pastraipą: 2 tarpai.

**Comment by Bebrazmogis** [comment]
Oh right čia yra ir dar viena klaida aprašyta..... Geriau būtų vienas issue - viena klaida :/

**Comment by Yiin-** [comment]
tai sukuri naują issue ir čia referencini jį, o šitą uždarai.

**Comment by SkepticalHippo** [comment]
@Bebrazmogis @Yiin- 

![](https://i.imgur.com/h8cNahZ.png)

Referenced and closed.

Šitas irgi išspręsta jau kaip supratau.
