### ISSUE TITLE
Editoriui placeholderis

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#32]
Lėtai scrollinant, ypač mobile versijoj, kai editorius prikimba ekrano viršuje visas contentas po juo pakyla maždaug per du vienos eilutės postus. Šiek tiek galima praleist turinio taip, tad siūlyčiau įdėt editoriaus placeholderį kuris prikibus editoriui taptu tuščia vieta (tokio height kokio editorius yra) ir nebūtų to content jump

**Comment by SkepticalHippo** [comment]
Good catch.

**Comment by SnoutUp** [comment]
Prie to paties: papostinus trumpą atsakymą browseris jį fokusuoja ir naujo atsakymo forma jį visą tiesiog uždengia.

**Comment by PovilasLT** [comment]
@SkepticalHippo - jei jau turėjo įsigaliot, tai kažkodėl neveikia :?

**Comment by SkepticalHippo** [comment]
Betoje turėtų būt.

-- 
Edvinas Paulauskas
Sent with Airmail

On 8 January 2016 at 00:03:58, PovilasC (notifications@github.com) wrote:

@SkepticalHippo - jei jau turėjo įsigaliot, tai kažkodėl neveikia :?

**Comment by PovilasLT** [comment]
@SkepticalHippo - nop, kaip buvo taip ir yra, peršoka per du postus kai editorius prisikabina viršuj.

**Comment by SkepticalHippo** [comment]
Ne placeholderis, bet sutvarkytas peršokimas į pranešimus.

-- 
Edvinas Paulauskas
Sent with Airmail

On 8 January 2016 at 00:07:05, PovilasC (notifications@github.com) wrote:

@SkepticalHippo - nop, kaip buvo taip ir yra, peršoka per du postus kai editorius prisikabina viršuj.

**Comment by PovilasLT** [comment]
@SkepticalHippo neatsižvelgei į tai, kad mobile editorius yra su didesniu height, todėl dabar pusė pranešimo tik matosi

![Imgur](http://i.imgur.com/xQ6xxhY.jpg)
