### ISSUE TITLE
linkų atsidarymas naujame skirtuke

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#33]
siūlyčiau pridėti target blank ant linkų postuose, daug patogiau.

**Comment by SkepticalHippo** [comment]
@Bebrazmogis @Rinkuns @Yiin-

**Comment by Rinkuns** [comment]
Na jei tai diskusija tai padiskutuokime. Esmė tame, kad yra tokia galimybė open in a new window/tab, bet kartais vienas paspaudimas būtų paprasčiau negu du. Tai aš už.

**Comment by SkepticalHippo** [comment]
@Rinkuns laikyk CTRL spaudžiant ant nuorodos. Atidarys naujam tab'e iš karto. Bet fair deuce. Sumažintų žmonių išeinančių iš forumo kiekį. Aš iš dalies už, bet tik kitoj versijoj.

**Comment by PovilasLT** [comment]
spaudžiant pelės ratuką instant atidaro naujam skirtuke, bet mobile versijoj nelabai patogu.
ir dar idėja uždėt rel="nofollow" ant nuorodų

**Comment by SkepticalHippo** [comment]
@PovilasLT kitoms įdėjom atidaryk naujus "Issue", taip bus lengviau susigaudyti, kas jau padaryta, ir ką dar reikia nuveikti. Ir diskusijas atskirti daug patogiau bus :)
