### ISSUE TITLE
"WWWWW" testas sulaužė breadcrumbsus

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#35]
http://beta.maze.lt/tema/3406-wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

**Comment by SkepticalHippo** [comment]
Sulaužo, nes wwwwwwwwwwwwwwwwww...w yra skaitomas kaip vienas žodis. Realaus scenarijaus tokio neturėtų būti. Kitais atvejais kiekvieną žodį rašys iš naujos eilutės, nebent žodis labai ilgas (bet vietos turėtų užtekti).
