### ISSUE TITLE
Rodo bloga data kai kanors parašai ar sukuri tema 

### ISSUE THREAD

**Issue by Paganas** [SkepticalHippo/maze#36]
Su Mozilla Firefox rodo bloga temų ir pranešimu sukūrimo/parašymo laika, bet su Google Chrome viskas ok 

http://www.part.lt/img/28e3a10b6566b74799a8d0b8d22f638a313.png

http://www.part.lt/img/397d31d324f87c80149c1f37b787076f175.png

**Comment by SkepticalHippo** [comment]
#63
