### ISSUE TITLE
Didžiosios/mažosios neturėtų būt svarbios paminėjimuose

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#37]
Šiek tiek erzina, kad pradedant rašyti @e neautocompletina @Edvinas. Gal net ne šiek tiek. Manau, kad ir į lietuviškas raides (jei jos leidžiamos nickuose) taip pat atlaidžiau tegul tas skriptas žiūri.

**Comment by SkepticalHippo** [comment]
Yeah, šitą ir pats svarsčiau. Su visa ta front-end betvarke reikės smarkiai padirbėti ateinančiuose releasuose.

**Comment by SkepticalHippo** [comment]
47f17d0fcf09628daba23f4399780e7395c48090
