### ISSUE TITLE
PM notification pašaliniams esant pokalbio puslapyje

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#38]
Rašinėjausi su Edvinu. Buvau atsidaręs pokalbį. Jis man parašė. Gavau notification. Refreshinau chato puslapy. Notification nedingo.

Dingsta tik tada kai žiūri į sąrašą PM.

**Comment by SkepticalHippo** [comment]
Dingsta tik tada, jeigu atrašai į žinutę. Kaip tavo manymu būtų geriau?

**Comment by PovilasLT** [comment]
mano mažai vertinga nuomonė sako jog būtų geriau vos peržiūrėjus

**Comment by SkepticalHippo** [comment]
1. Žmogui palikus socket.io kanalą siųsti užklausą į MySQL ir pasakyti, kad žinutės perskaitytos iki būtent to laiko. (tikriausiai reikėtų MySQL prisijungimo notification.server.js). Visas veiksmas vyksta serverio pusėje.
2. Su kiekviena gauta žinute iš kliento siųsti užklausą į serverį, kad žinutė gauta ir perskaityta. Veiksmas vyksta pas klientą ir eina į serverį.

Ką manot?

**Comment by PovilasLT** [comment]
maybe 2? lengviau didelių apkrovų atveju būtų serveriui

**Comment by Yiin-** [comment]
na pirmu atveju serveris mažiau užklausų gaus, bet su antra turėtų geriau veikti jeigu forumas per daugiau negu 1 langą atidarytas.

**Comment by SkepticalHippo** [comment]
e483ac3a0cf048b99e7b672d99da6c58006f4f87
