### ISSUE TITLE
nerodo avatatų

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#40]

**Comment by PovilasLT** [comment]
whoops netyčia išsisiuntė :D nerodo avatarų, android 5 chrome 41

**Comment by PovilasLT** [comment]
![Imgur](http://i.imgur.com/41roslh.jpg)

**Comment by SkepticalHippo** [comment]
Įdomiai. Kol pilnai nepamačiau, galvojau, kad kalbi apie avatarus, kurie prie teksto redagavimo formos būna :D

**Comment by PovilasLT** [comment]
Po perkelimo iš beta subdomenl viskas susitvarkė, closinu, jei pasikartos sukursiu naują su daugiau info :)

**Comment by PovilasLT** [comment]
beta forume vistiek nerodo, gal ir small shit, bet tvarkyt!

**Comment by SkepticalHippo** [comment]
@Yiin- susiję su 57cdca6b5c3fb105e83ec218ff96f9ac72cf7aa1 ir c661d911833c32a0330222b71b3235ebf8a5787c iš beta branch?
