### ISSUE TITLE
populiariausi ir naujausi be page refresh maybe?

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#41]
būtu sūper jei populiariausi ir naujausi būtų kaip tabs, kad nereiktų refreshint, taip pat būtų galima nusistatyt primary (jei aš atėjęs į maze noriu matyt naujausius pranešimus, po galais kodėl turiu kažkur clickint???)

**Comment by SkepticalHippo** [comment]
Good point. Bet gali būt, kad reikės palaukti šito. Palieku klausimą atvirą diskusijoms :)

**Comment by Bebrazmogis** [comment]
Aš už!

**Comment by SkepticalHippo** [comment]
Integruota su PJAX. Ateis kartu su 2.1

Iš esmės, visi puslapiai persikraudinės be pilno refresh, o tik pasiimdami tą, ko reikia iš sekančio puslapio.
