### ISSUE TITLE
chrome push notifications?

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#42]
ką jūs apie tai kad uždarius maze gautum pranešimus ant desktopo? like delfi, tikrai naudingas dalykas. Galima ir į ragelį taip nusistatyt. https://goroost.com/try-web-push ar kažkas panašaus

**Comment by SkepticalHippo** [comment]
Iš dalies panašu į #43

**Comment by SnoutUp** [comment]
GoRoost kainuoja (minimum 30-40$/mėn berods anksčiau buvo) ir, šiuo metu, ten chaosas lengvas. Nemokamo serviso normaliems desktop pushams, as far as I know, nėr. O paprasti, kur veikia tik naršant konkrečią svetainę, tai tikrai čia nereikalingi, kai galima su JS ką nors gražesnio parodyt atsiradus naujam pranešimui.

**Comment by PovilasLT** [comment]
@SnoutUp - turint tokią profų komandą kaip turi maze, manau patys galėtų pasidaryt :D
