### ISSUE TITLE
Žinučių išstūmimas į atskirą "platformą"

### ISSUE THREAD

**Issue by SkepticalHippo** [SkepticalHippo/maze#43]
Kadangi dabar turim infrastruktūrą tam, turim galimybę išstumt maze žinutes į visiškai kitą "platformą" ir padaryti atskirą "maze messenger".

Per daug darbo nereiktų. CSS turim, galim viską sukonstruot su HTML ir supakuot kaip mobilią ir desktop programėles vienu smūgiu.

Kokios nuomonės?

**Comment by PovilasLT** [comment]
gal tuomet tiesiog maze appsas android/ios/wp?

**Comment by SkepticalHippo** [comment]
Pilnas appsas per daug priežiūros reikalautų. Labai laikas ir resursai mūsų riboti. Bet išstųmus tik vieną dalį nedidelę, visai įmanoma dar.

**Comment by PovilasLT** [comment]
jei tik dėl vienos dalies, nemanau kad apsimoka daryt appsą, kurio atsisiuntimas ir įdiegimas daugiau laiko užimtų nei jo kasdienis naudojimas :D aš tada už #42, paspaudi leisti ir gauni notificationus apie žinutes ir maze naujienas maybe?

**Comment by PovilasLT** [comment]
reikia kitų nuomonės :)

**Comment by Rinkuns** [comment]
Gaila, kad nėra, nes būtų tikrai įdomu sužinoti ar naudotųsi tokiu dalyku. Aš asmeniškai nieko prieš neturiu naują platformą, bet chrome notificationai atrodo irgi labai gundančiai, bet kaip ir minėjo Povilas vien dėl vienos funkcijos naujos platformos gal ir nereiktų stumti į šviesą, reiktų galbūt padirbėti dar, pridėti kokių nors awsum funkcijų ir tik vėliau išleisti šį patobulinimą.
All in all,
notificationai galėtų būti sukurti dėl temų, sekamųjų naujienų, o messengeris dėl pranešimų.

**Comment by nofkingideaforname** [comment]
Nesutinku dėl chat, jeigu kas ir naudotų tokį dalyką, tai jis atstotų buvusius būsenų pranešimus ir niekas nekurtu temų, dėl notifications 50 / 50. Jeigu duosi laisve žmonėms su visais nustatymais kada rodyt kada ne tada aš už, atsirastų daugiau lankytojų/d

**Comment by PovilasLT** [comment]
@nofkingideaforname - nelabai supratai chat esmę. Chatas tarp dviejų žmonių čia. O būsenų pranešimai niekur nedingo :)

**Comment by nofkingideaforname** [comment]
Tuomet koks tikslas jeigu tarp dviejų žmonių? Žinučių sistema taip pat tarp dviejų žmonių ir jokio latency nėra.
