### ISSUE TITLE
vartotojo vardo pasikeitimas?

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#44]
#29 closed bet nerandu kaip pasikeist vartotojo varda. ar aš durnas ar čia tik staff gali?

**Comment by Rinkuns** [comment]
http://maze.lt/slapyvardis/keisti
Bandyk eiti per čia.

**Comment by PovilasLT** [comment]
Hm, gavosi. Tuomet performuluoju - pridėt linką nustatymuose vartotojo vardo keitimui, kadangi ten dauguma ir ieškos mano manymu

**Comment by SkepticalHippo** [comment]
2adc39b1f5d2913f22b842ef7053d9ec87f5ce8a

**Comment by PovilasLT** [comment]
@SkepticalHippo - maybe jei jau esi pasikeitęs savo vartotojo vardą, rodyt tą laukelį tačiau su žinute, kad jau esi išnaudojęs keitimus?

Tu jau esi išnaudojęs savo nemokamą vartotojo vardo pasikeitimą!

**Comment by SkepticalHippo** [comment]
Vardą gali keisti tik tie, kas užsiregistravo prieš maze 2.0, tai nelabai yra esmės dėti tą :) Jeigu nerodo - reiškia negali keisti. Labai paprasta sakyčiau :)
