### ISSUE TITLE
Prikibęs editorius - atitraukti nuo kraštų (mobile)

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#45]
![Imgur](http://i.imgur.com/FE2xjes.jpg) -neprilipęs

![Imgur](http://i.imgur.com/UMVNODd.jpg) - prilipęs

gražiau atrodo kai nuo kraštų atitraukta, bent jau man, ir tuomet ne taip matysis perėjimas kai editorius prikimba :)

tuo pačiu #32

dar nenusibodau su savo issues? :(

**Comment by Bebrazmogis** [comment]
Kai kalbi apie prikibą tu apie tai kad jis keliauja kartu kai scrollini?

**Comment by PovilasLT** [comment]
taip, na sticked on top, ir kai jis ten prikimba dingsta tarpai nuo kraštų (šonų). Išsiplėčia jis kažkiek

**Comment by Bebrazmogis** [comment]
"It's not a bug, it's a feature". Taip padaryta kad patogiau būtų atrašinėti.

**Comment by PovilasLT** [comment]
bett gražiau atrodytų jei jis neišsiplėstų per kraštus
