### ISSUE TITLE
Oj, kažkas netaip?

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#50]
![img](http://puu.sh/mmNZe/1943db7253.png)
![img](http://puu.sh/mmO0R/3b99906c3a.png)
čia dabar kas per fokusai? Vakar keičiausi slapyvardį, gal dėl to?
beta forume viskas gerai (išskyrus #40)

**Comment by SkepticalHippo** [comment]
Kokiu maždaug laiku ir ar vakar ar šiandien toks dalykas įvyko?

**Comment by PovilasLT** [comment]
vakar po nick keitimo viskas buvo gerai, šiandien nebeleidžia. Pastebėjau ir iškart issue sukūriau.

**Comment by PovilasLT** [comment]
tuo pačiu pataisykit klaidą šitam užraše - **informkuotie** administraciją (dėl vieno žodžio nemanau kad verta issue daryt, o gal?)

**Comment by PovilasLT** [comment]
nustatymai ir viskas kita veikia, neveikia tik /profilis ir  /vartotojas/rileyw1 
Kitų userių profiliai veikia.

**Comment by SkepticalHippo** [comment]
Ar trynei pranešimus kokius nors?

**Comment by PovilasLT** [comment]
Man atrodo, kad taip, tačiau tiksliai tikrai nepasakysiu, i'm sorry.
/profilis jau veikia, tačiau /vartotojas/rileyw1 dar ne

**Comment by SkepticalHippo** [comment]
Būtų gerai, jeigu kai išmeta tą "Oi" klaidą, tiksliai surašytum ką ir kaip darei prieš tai. Tada lengviau ieškoti klaidų būna ir jas greičiau ištaisyti :)

**Comment by PovilasLT** [comment]
Hm.. atgaminsiu tikriausiai
naktį browsinau forume, pasikeičiau nicką, parašiau keletą postų, vieną ištryniau, bet nepastebėjau nieko. Šiandien užėjau į forumą, peržiūrėjau temas, nuėjau į savo profilį, ir gavau šitą klaidą, kad ir kiek beeičiau į jį. Atsijungus irgi meta tą patį. http://maze.lt/vartotojas/rileyw1

**Comment by SkepticalHippo** [comment]
Ok. Ačiū. Einu bandyti sutvarkyti :)

**Comment by SkepticalHippo** [comment]
Sutvarkyta.
