### ISSUE TITLE
/profilis ir /vartotojas/xxxx ta pati funkcija

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#51]
Kažkiek galima pasimest, kuo skiriasi /profilis ir /vartotojas/xxxx (tavo nickas). Siūlyčiau padaryt taip, kad pamygus ant savo avataro mestų į /profilis, nes tas /vartotojas/xxxx vos ne tas pats langas, tik su daug mažiau funkcijų. Lengva pasimest labai.

**Comment by SkepticalHippo** [comment]
@PovilasLT bet tokiu atveju, sunku lengvai patekti į save /vartotojas/xxx puslapį.

**Comment by Yiin-** [comment]
2d19c057fc4ad03f15cdd00d000f451b9feb753e

fixed jau nuo vakar

**Comment by Yiin-** [comment]
@SkepticalHippo galima savo profilyje padaryti linką kaip facebook padarė "View as public" kur parodo kaip tave mato kiti žmonės.

**Comment by SkepticalHippo** [comment]
Taip ir padarom tada.
