### ISSUE TITLE
Prilipęs šoninis meniu (desktop)

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#52]
Visai būtų nieko jei šoninis meniu būtų prilipęs, panašiai kaip http://getbootstrap.com/css/ tik be tų išsiskleidinėjimų. Nes ilgoje temoje kažkiek nepatogu atgal į viršų scrollint kad tą meniu pasiekt.

**Comment by SkepticalHippo** [comment]
Gera mintis. Tikriausiai įdėsim :)

**Comment by SkepticalHippo** [comment]
Turėtų būt betoje jau. Reikia papildomų testų. Jeigu kažkas neveiks - naujas issue.
