### ISSUE TITLE
[Beta] skaičiai profilio linke

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#53]
http://beta.maze.lt/vartotojas/rileyw1532532532532532532532532532532532532532532532532532532532532532532532532532532532532532532532

su kiekvienu pamygimu ant avataro prisideda gale linko papildomas 532532. Einant į kitų profilius same, tik kiti skaičiai. Gal čia user ID?

**Comment by SkepticalHippo** [comment]
fdbea0dfc8f5c22e0f14142713e6da4cade0e715
