### ISSUE TITLE
[Beta] Keičiantis avatarą - Oi!

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#54]
Bandant keistis avatarą, pasirinkus naują ir pamygus išsaugoti, nukelia į http://beta.maze.lt/profilis/nustatymai/issaugoti ir išmeta tą Oi! klaidą.
Ar čia susiję su #40? vienam čiūvui (http://beta.maze.lt/vartotojas/rodriges257) rodo avatarą, kitiem ne, tai keista, galvojau kad pasikeitus ir mano rodys. Jei #40 tuomet atsiprašau.

**Comment by SkepticalHippo** [comment]
Čia dėl to, nes betoje išsitrynė visi avatarai. Pažiūrėsiu kodėl ta klaida įsivelia, gal bus kažkokia rimtesnė problema.

**Comment by PovilasLT** [comment]
Keista jei išsitrynė tai, kad neleidžia naujų uploadint :/
