### ISSUE TITLE
Užtaginimai neveikia su spec. simboliais

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#56]
Pabandžiau užtagint žmogų, kurio nickas So Good√ιק
Parašiau @, išmetė to žmogaus nicką, pamygau, išsugojau.
Užtaginimas nesuveikė.
I'm upset.

**Comment by SkepticalHippo** [comment]
@PovilasLT dėl to ir yra privalomas vardo pasikeitimas tiems, kurių vardai turi tokių simbolių :) Ilgainiui, tiems, kurie nepasikeis vardų - pakeisim patys. Tai problema išsispręs su laiku :)
