### ISSUE TITLE
Skirtingos citatos susilieja į vieną

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#57]
![image](http://puu.sh/mn54J/ccc93602dc.png)

![image](http://puu.sh/mn570/52da6edf68.png)

Padėjus du tarpus po pirmos vistiek atrodo kaip viena citata. ![image](http://puu.sh/mn5cH/65a454c453.png)

jei atsibodau su savo issues sakykit :D

**Comment by SkepticalHippo** [comment]
Viskas gerai. Kaip tik smagu, kad yra prisidedančių :)

Jeigu palieki tuščią eilutę tarp citatų, vis tiek tas pats?

**Comment by PovilasLT** [comment]
tada viskas ok, nepagalvojau :D ir net tarpų nereikia. Tuomet gal editoriui pamygus citatą ieškot ar nėra citatos viršui, jei yra - prideda tuščią eilutę? Nors, nebūtina

**Comment by SkepticalHippo** [comment]
Sulieja citatas, nes kartais, kad citatos nesusibugintų, reikia naujoj eilutėj padėti vėl citatos ženkliuką. Bet čia pagal situaciją.
