### ISSUE TITLE
Dizainas?

### ISSUE THREAD

**Issue by Optimist78** [SkepticalHippo/maze#58]
Labas. Nežinau ar jau kas nors šitą rašė ir nežinau kaip kitiems, tačiau man asmeniškai telefone reikia funkcijos „Switch to Desktop version“ nes mane asmeniškai šiek tiek nervina, kad nerodo šių dalykų iškart (o kad reikia paspausti ant to žalio dalykėlio) :

![image](https://cloud.githubusercontent.com/assets/16598956/12180930/3735ddb0-b577-11e5-90da-243facd4ea62.png)

![image](https://cloud.githubusercontent.com/assets/16598956/12180944/46794172-b577-11e5-988d-6ea758742c87.png)

Žinoma, tai nėra būtina, tačiau vis vien, to reiktų, nes jei ir kažkas pasikeistų, man labiau patiktų būti kompiuterinėje versijoje, kadangi telefono versijoje viskas atrodo labai sugrūsta. Ačiū, kad sugaišote savo laiką skaitydami šį pasiūlymą.

**Comment by PovilasLT** [comment]
Matai, versija ta pati, čia labiau responsive dizainas yra. Tačiau nieko nėra neįmanomo :)

**Comment by Optimist78** [comment]
@PovilasLT Tu sakai, tu žinai. Kaip pats paminėjai „nieko nėra neįmanoma“, tad manau bus padaryta ^^

Realiai, galbūt ir būtų ok tas dizainas, tačiau kai ant iPhone ekrano dydis yra 4.0", tai gaunasi susigrūdę viskas, ir išties neatrodo labai patraukliai.

**Comment by PovilasLT** [comment]
Tuomet bent kolkas, kad būtų patogiau patarčiau šonu pakreipus telą naršyt :D 
![t](http://static.fjcdn.com/pictures/Skeptical_87506e_127195.jpg)

**Comment by Optimist78** [comment]
@PovilasLT taip ir darau :D

**Comment by SkepticalHippo** [comment]
Dizainas yra responsive ir prisitaiko automatiškai prie ekrano dydžio/rezoliucijos. Gal ir būtų kažką įmanoma padaryti, bet geriau tobulintume dabartinį mobilų dizainą, negu žaistume su galimybe įjungti/išjungti mobilų dizainą.

Pažiūrėsiu, bet nieko nepažadu. Kol kas uždarau issue.
