### ISSUE TITLE
[Beta] Viešas profilis - Oi!

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#60]
Nesiseka man su tais profiliais.. :D
Nuėjus į viešą profilį betoj meta Oi!
![img](http://puu.sh/mnbmg/21d704783d.png)

**Comment by SkepticalHippo** [comment]
Trynei pranešimą?

**Comment by PovilasLT** [comment]
Taip, kai citatas pranešinėjau buvau sukūręs [šioje temoje](http://beta.maze.lt/tema/apklausa-kuris-zaidimas-jums-patinka-labiausiai), po to ištryniau.

**Comment by SkepticalHippo** [comment]
ar buvo paminėjimų pranešimuose?

**Comment by PovilasLT** [comment]
@TesT buvo paminėtas.
![img](https://camo.githubusercontent.com/9fdff6f555b270b0bfd908fa06a60ae5c98a4601/687474703a2f2f7075752e73682f6d6e3563482f363561343534633435332e706e67)

**Comment by SkepticalHippo** [comment]
Aišku. Ir trindamas pranešimą klaidos negavai jokios?

**Comment by PovilasLT** [comment]
Nop, parašė kad pranešimas ištrintas sėkmingai, or something like that (nu ta žalia lentutė)

**Comment by SkepticalHippo** [comment]
Gerai. Dėkui.

**Comment by SkepticalHippo** [comment]
d3c9d49e8478012f71f7d21419501927557c1db3
