### ISSUE TITLE
Sąrašai neveikia :/

### ISSUE THREAD

**Issue by Optimist78** [SkepticalHippo/maze#61]
Peržiūrinėjau senąsias temas, ir hmmm... Pastebėjau, kad sąrašai nebeveikia:

![image](https://cloud.githubusercontent.com/assets/16598956/12181604/340eed3a-b57b-11e5-9444-27601132c272.png)

**Comment by SkepticalHippo** [comment]
Ne sąrašai, o lentelės. CommonMark nenaudoja lentelių visiškai. Prie to paties, lenteles labai sunku perteikti mobiliuosiuose.

**Comment by Rinkuns** [comment]
Si tema neneaudojo markdown saraso funkcijos. Viskas buvo daroma su enter perkelimu.

**Comment by Optimist78** [comment]
@SkepticalHippo tas jausmas, kai pamiršai lietuvių kalbą po 2 metų gyvenimo anglijoje...
