### ISSUE TITLE
Online useriai?

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#65]
Galbūt tolimai ateičiai - Online userių sąrašas (nebūtina), žalias, raudonas, arba pilkas rutuliukas profilyje ir/ar prie temų, ir paskutinio prisijungimo data su galimybe nusistatyt kad ją slėptų?

**Comment by SkepticalHippo** [comment]
Prisijungimo data, taip. Bet žiūrėti ar žmogus online ar ne, kaip ir nėra reikalo. Kadangi forumo pagrindinė esmė ir yra palikti žinutę ir tada eiti veiktį kažką kito. Asmeninėse žinutėse gal ir būtų visai nieko toks variantas. Pagalvosim dar :)
