### ISSUE TITLE
Meniu pasidarė scrollable mobile. Bug?

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#68]
![Imgur](http://i.imgur.com/G6gt20L.jpg)

scrollable meniu po to atnaujinimo pasidarė. anksčiau užimdavo pilną savo aukštį, dabar 100% ekrano tikriausiai.

**Comment by SkepticalHippo** [comment]
Laikinai išimu. Šoninio meniu prisegimui reikės kažką kito galvoti. Naudojamos technologijos nelabai tinka, nes turinys per ilgas.

Kol tyrinėjami galimi sprendimo variantai laikinai išimu iš beta.
