### ISSUE TITLE
Laiko skaičiavimo klaida (Windows IE ir MS Edge)

### ISSUE THREAD

**Issue by Optimist78** [SkepticalHippo/maze#71]
Visur rodo „Prieš kelias sekundes“:

**Internet Explorer**
![image](https://cloud.githubusercontent.com/assets/16598956/12206507/4bd6bd4e-b639-11e5-83d0-fde608cdc9ab.png)
![image](https://cloud.githubusercontent.com/assets/16598956/12206534/6bbb877a-b639-11e5-8825-7992dc6382b0.png)
---

**Microsoft Edge**

![image](https://cloud.githubusercontent.com/assets/16598956/12206604/c4206714-b639-11e5-88df-15aae45dbbd3.png)

Mačiau buvo #69 sukurta, tačiau ten WP, o čia Windows PC tai nežinau ar skiriasi kuo nors ar ne :x

**Comment by SkepticalHippo** [comment]
#63
