### ISSUE TITLE
Prieiga prie nustatymų

### ISSUE THREAD

**Issue by Optimist78** [SkepticalHippo/maze#73]
Siūlau padaryti, kad prieiti prie ``` http://maze.lt/profilis/nustatymai ``` būtų galima ir per čia: ``` http://maze.lt/vartotojas/optimist78 ```

Kadangi keista kažkaip, paspaudi ant ```Pranešimai``` (bent jau aš manau, kad ta icon'a reiškia ```Pranešimai``` (kaip per FB)) ir per ten reikia eit į nustatymus.. Na žodžiu, tokia smulkmenėlė.

**Comment by PovilasLT** [comment]
Nemanau, kad reikalinga. Juk sujungti profiliai beta forume dabar, tad neverta.

**Comment by PovilasLT** [comment]
#78 - sukūriau pull requesta kuris dar patogesnis nei tavo idėja ;)

**Comment by SkepticalHippo** [comment]
f4ec306eca82cf37843c591547f259dfa8ece4a3
