### ISSUE TITLE
Prisijungimas grąžintų į buvusią vietą - neveikia.

### ISSUE THREAD

**Issue by PovilasLT** [SkepticalHippo/maze#77]
#64 lyg tais ir įdėtas, tačiau neveikia vis dar, nei ant beta nei ant paprasto.
8ad54fd

**Comment by SkepticalHippo** [comment]
Prisijungimas nukreipia tik tada, kai platforma pati paprašo vartotojo prisijungti. Pvz paspaudus "Kurti naują temą". Bet supratau, kad reiktų jog gražintų paspaudus "prisijungti" bet kada?

**Comment by PovilasLT** [comment]
Būtų daug patogiau, nes kaip ir aiškinau ankščiau, atsidarius temą pamygi prisijungti ir tave nukelia į pagrindinį :/
