### ISSUE TITLE
Kurti tema mygtukas

### ISSUE THREAD

**Issue by codemenas** [SkepticalHippo/maze#8]
Kurti tema mygtukas mobiliojoje versijoje yra neprisijungus.

**Comment by SnoutUp** [comment]
Neprisijungus desktop'e "Kurti temą" veda į "502 Bad Gateway". Galėtų vest į login puslapį su buvusios vietos išsaugojimu.

**Comment by SkepticalHippo** [comment]
8e8c790c64416d0f1a264e9952976d87c8720184
