### ISSUE TITLE
Nerodo kas paminėjo ir kur

### ISSUE THREAD

**Issue by PositiveGR** [SkepticalHippo/maze#82]
Kada tave pamini ir jei tu neseki to žmogaus tai tiesiog nerodo, kad tave pamini, arba aš toks aklas... Kada tu tą žmogų seki - viskas ok, parodo. Bet jei ne - nerodo...

**Comment by SkepticalHippo** [comment]
Nuėjus į "Paminėjimai" irgi nerodo?

**Comment by PositiveGR** [comment]
Nu kad ne... http://www.part.lt/img/aaa41ff8ad056d6183b3855d7150593d772.png čia turėtų rodyti kokius 6 manau...

**Comment by SkepticalHippo** [comment]
Aišku. Ačiū. Taisysim :)

**Comment by PovilasLT** [comment]
prisidedu prie šito - 
![i](http://puu.sh/mpgKZ/940fb4fc7f.png)

Rodo tuščią, laikas atitinka maze 2.0.1 temos kur minėjai mane
