### ISSUE TITLE
Blogai rodo kieno paskutinis atsakymas

### ISSUE THREAD

**Issue by PositiveGR** [SkepticalHippo/maze#83]
![untitled](https://cloud.githubusercontent.com/assets/14017466/12216296/2a7b1cd8-b6e5-11e5-98e0-1ae38655a330.png)
Rodo taip, nors temoje paskutinis yra Flax.
![untitled](https://cloud.githubusercontent.com/assets/14017466/12216299/3eb309cc-b6e5-11e5-95f7-b71a5080bb40.png)

**Comment by SkepticalHippo** [comment]
Nuorodą į temą?

**Comment by PositiveGR** [comment]
http://maze.lt/tema/17066-c-dienu-skaiciavimas

**Comment by SkepticalHippo** [comment]
ačiū
