### ISSUE TITLE
@Galardas - pažymėjimai kažkaip netaip veikia..

### ISSUE THREAD

**Issue by Gerardas** [SkepticalHippo/maze#86]
Mane pažymėjai po tema Maze atnaujinimai 2.0.1, bet aš pamačiau per kito žmogau ss. Niekur nieko nemetė. Čia po apačia(kitam issue) yra ss įkeltas ir ten esu pažymėtas. O kitose temose rodo, kad mane pažymėjo. Bet tu kai pažymėjai nerodo. Klaida, ne klaida nežinau gal jau tvarkot, bet pastebėjimas mano toks.

**Comment by PovilasLT** [comment]
galėjai prirašyt prie to pačio, klaida juk ta pati, kam naujas issue? #82

**Comment by Gerardas** [comment]
Atsiprašau, nepastebėjau. :)
