### ISSUE TITLE
Paspaudus ant profilio meta klaidą

### ISSUE THREAD

**Issue by Gerardas** [SkepticalHippo/maze#87]
http://i.imgur.com/PqVI1xU.jpg

**Comment by SkepticalHippo** [comment]
Vis dar rodo?

**Comment by Gerardas** [comment]
Taip

**Comment by SkepticalHippo** [comment]
Atsiprašau. Gali būti, kad čia dėl prieš tai buvusio spamo ir įsivėlė klaida.

**Comment by Gerardas** [comment]
www.maze.lt/profilis meta, nors norint į profilį man įjeiti reikia eiti http://maze.lt/vartotojas/galardas241

**Comment by SkepticalHippo** [comment]
www.maze.lt/profilis - yra tavo privatus profilis.

www.maze.lt/vartotojas/galardas241- yra tavo "viešas" profilis.

**Comment by Gerardas** [comment]
Nu tai man privataus tada vadinas nerodo..

**Comment by SkepticalHippo** [comment]
Pataisiau. Turėtų rodyti. Pabandysiu padaryti ką nors, kad daugiau tokių dalykų nebeatsitiktų. Dar kart atsiprašau už nesklandumus.

**Comment by Gerardas** [comment]
Taip, veikia. Viskas yra gerai tam ir padedam, kad tobulėtumėm. :)

**Comment by Gerardas** [comment]
Sveikas dar kartą,
Tikrai nenoriu įkyrėti, bet kaip supratau mano githube issue yra pažymėtas
kaip sutvarkytas. "Gramatinės klaidos" Nors niekas nepakeista ;s..
Žinau, kad turit svarbesnių reikalų..

2016-01-10 1:51 GMT+02:00 Edvinas <notifications@github.com>:

**Comment by SkepticalHippo** [comment]
Sutvarkyta betoje. Reiskia tuoj pereis ir i pagrindini :)
