### ISSUE TITLE
Etiketo papildymas.

### ISSUE THREAD

**Issue by Rinkuns** [SkepticalHippo/maze#9]
Prie etiketo dabar būtų gerai prirašyti:
"Neprikelti temų su "up" ar panašaus tipo pranešimais."

**Comment by SkepticalHippo** [comment]
@Bebrazmogis arba @Yiin- galit šitą padaryt.

**Comment by Bebrazmogis** [comment]
#8fab3d4f147a185ad8e5280bd19e8e075a26ffd6
