### ISSUE TITLE
Labai lengva bug'inti peržiūras

### ISSUE THREAD

**Issue by PositiveGR** [SkepticalHippo/maze#91]
Įeini į temą ir laikai F5, ir eina peržiūros. Tai nežinau... Norisi, kad būtų kažkoks delay kai užkrauna puslapį ar pnš. Nes db tai... Populiariausią temą lengva padaryti. Pavyzdžiui - http://maze.lt/tema/17345-serverio-ideja

**Comment by SnoutUp** [comment]
Čia klausimas būtų, kaip skaičiuojamas temos populiarumas? Yra kokie nors svoriai skiriami peržiūroms/įvertinimams/komentarams ar populiarumo "nykimas" bėgant laikui?

**Comment by PositiveGR** [comment]
@SnoutUp man irgi įdomu pasidarė. Nes nemanau, kad tik pagal peržiūras tai skirstoma.

**Comment by PovilasLT** [comment]
![](http://puu.sh/mqy8l/b755b43034.png)

Peržiūros iš vis nieko nelemia populiariausių sąraše (nebent labai mažą dalį)

Karma ir atsakymai pagrindinis kriterijus

**Comment by SkepticalHippo** [comment]
Peržiurų kiekis neturi visiškai jokios įtakos temos populiarumui. Ten tiesiog bendras rodiklis, labiau skirtas temos autoriui, parodyti kiek kartų jo tema peržiūrėta.

Temos rikiuojamos pagal svorį. Pagrindiniai kriterijai yra balsai ir pranešimų kiekis. Temos svorį praranda kas valandą ir krenta iki nulio, kur būna išrikiuojamos pagal tai, kada jos buvo sukurtos. Skandintos temos turi -1 svorio, dėl to jos bus dar žemiau, negu įprastai.

Aš dažniausiai net ignoruoju tą peržiūrų skaičių. Tiesiog buvusioje versijoje kažkas minėjo, kad įdomu matyti tokius dalykus. Jeigu kažkam niežti nagai laužyti peržiūras, pirmyn, nes nelabai kam ir kenkia, o tiesiog naudoja savo laiką :)
