### ISSUE TITLE
Po chat'o lieka notifications

### ISSUE THREAD

**Issue by PositiveGR** [SkepticalHippo/maze#92]
Kai bendrauji per PM, viskas vyksta ten live. Bet po to nueini į main'ą ir rodo notifications vis tiek. 
![untitled](https://cloud.githubusercontent.com/assets/14017466/12221694/72144bf4-b7ae-11e5-973f-964b597a5865.png) lyg nebučiau buvęs ten.

**Comment by PovilasLT** [comment]
#38
