### ISSUE TITLE
Temos sukūrimo data temoje skiriasi nuo temos sukūrimo datos profilyje

### ISSUE THREAD

**Issue by Bebrazmogis** [SkepticalHippo/maze#94]
http://maze.lt/tema/mysql-r33-beda <- prieš mėnesius
http://maze.lt/vartotojas/naikintojas836 <- prieš dieną

**Comment by PovilasLT** [comment]
ne tą temą atsidarei, http://maze.lt/tema/17064-mysql-problema iš profilio nukreipia @Bebrazmogis . Tiesiog panašios temos.
