### ISSUE TITLE
Pranešimai apie netinkamą turinį

### ISSUE THREAD

**Issue by Optimist78** [SkepticalHippo/maze#95]
Šiandien pastebėjau, kad niekur nėra pranešimo funkcijos, t.y. kaip pranešti kažkokį etiketo pažeidimą (i.e. keiksmažodžiai ar bet koks netinkamas turinys), tad siūlau tai sukurti.

**Comment by Bebrazmogis** [comment]
Kol kas gali parašyti administracijai AŽ. Ateityje gal kažkas ir atsiras, nors planuose kol kas nėra.
