### ISSUE TITLE
Keiksmažodžiai

### ISSUE THREAD

**Issue by Optimist78** [SkepticalHippo/maze#96]
Siūlau, jei įmanoma, sukurti ar bent jau pasvarstyti apie keiksmažodžių filtrą. T.y. jei kažkur kas nors pamini keiksmažodį, jį pakeičia į kokį tai nors žodį, pvz. ****Keiksmažodis****

Edit: Pritariu @SnoutUp, geriau tegul būna *

**Comment by SnoutUp** [comment]
Tik ne žodį... Supergames taip daro ir atrodo baisiau, nei patys keiksmažodžiai. Jeigu keist tai gal replace'int žvaigždutėmis... arba banint visus iš eilės! :)

**Comment by Rinkuns** [comment]
Kolkas keiksmažodžiai bei netinkamas turinys yra prižiūrimi moderatorių. Spėju, kai jau patys moderatoriai nebepajėgs susitvarkyti bus sukurta sistema, kuri pradės filtruoti tai, bet viskas priklauso nuo Edvino todėl mano teiginys gali būti paneigtas ateityje.

**Comment by SkepticalHippo** [comment]
Nemanau, kad keiksmus reikia filtruoti. Kol kas nėra labai opi problema su keiksmais. Jeigu nepatinka keiksmažodžiai ir manot, kad gadina visą pranešimą, galit dėti neigiamą karmą tam žmogui. Su laiku, manau padarysim, kad pranešimai, esantys žemiau tam tikro karmos lygio, būtų automatiškai suskleisti (peržiūrėti vis tiek bus galima).
