### ISSUE TITLE
Temos išskyrimo problemos

### ISSUE THREAD

**Issue by SnoutUp** [SkepticalHippo/maze#97]
Tęsiu "issues" ciklą pavadinimu "Kas man atrodo painu" ir šį kartą mano taikinyje - išskirtos temos. Megafono ikona labai sunkiai pastebima, nelabai tinkama (senas geras smeigtukas būtų aiškiau gal) ir galėtų būti kitoje vietoje (prieš antraštę galbūt? vietoj karmos? burbuliukas ant foto burbuliuko?).

Dabartinė išskirtoms temoms skirta pozicija (pirma populiariausiuose) yra gerokai per svarbi ir sugadina pačių sąrašų logiką. Kaip minėjau kažkurioje temoje, jas išskyrinėti gal būtų geriau pačiose kategorijose (League of legends konkursas - League of Legends kategorijoje) ARBA, in case of emergency, kažkur kitur (po "Sukurti temą" mygtuku, virš "populiariausi/naujausi" navigacijos) arba rodyti kaip dabar bet su išskirtinėm spalvom ar pan. Galbūt leisti vartotojui jas "atkabinti" pačiam? Man, tarkim, visai neaktualu kažkas susiję su LoL ar CS... :)

Taip pat, jų neturėtų rodyti naujausiuose, nes labai klaidina vartotoją ir, kartu, sukuria negyvo forumo vaizdą (smegenys parse'ina pirmą įrašą ir break'ina ciklą, jeigu jis senas).

**Comment by Optimist78** [comment]
Pridėsiu prie to - arba gilma tiesiog sukurti atskirą skiltį ar/ir subforumą "Konkursai"

**Comment by PovilasLT** [comment]
smeigtukas naudojamas local pin (pagal kodą galiu tiek pasakyt :D). Megafonas reiškia skelbimą, tai ką turėtų pamatyti visi

**Comment by SnoutUp** [comment]
Tai megafonas dabar reiškia "skelbimą" ir dar megafonas reiškia "pranešimą" ir dar  reiškia "išskirtą temą", kuri yra "prikabinta" arba "prismeigta" prie viršaus.

Okay then! :)

**Comment by SkepticalHippo** [comment]
Šiek tiek pakeičiau su 2a2f86ad42853c64eb6bb4e08bf46ea7736004cf

Pranešimas - temos tipas, kur žymima, dažniausiai, kažkokia svarbi informacija. Pakeista į žymėjimą šauktuku.

Yra du skirtingi temos prisegimai: globalus ir skilties. 

Globalus prisegimas dabar pakeis temos spalvą pagrindiniame sąraše. Dažniausiai naudojama irgi kažkokiai svarbiai informacijai komunikuoti, bet kuri būtų aktuali visai bendruomenei. Vis dar žymimas megafonu. LoL konkurso prisegimas nebuvo pats geriausias sprendimas.

Skilties prisegimas žymimas smeigtuku. Neiškelia temos pagrindiniame puslapyje, bet pažymi, kaip prisegtą skiltyje (neturi įtakos temos rikiavimui pagrindiniuose sąrašuose ir nėra pažymimas žalsva spalva).

Rašant kažką prie temos pavadinimo labai nekaip atrodo, ypač mobilioje versijoje, nes trukdo skaitymui. Visą mažiau aktualią informaciją stengiamės grūsti po temos pavadinimu.

Dėl aktualybių, jei neklystu, 2.0.2 turėtų leisti pasirinkti norimas prenumeruoti skiltis, kurios jau individualiai kiekvienam keis pagrindinio puslapio temas.

Šitas "issue" jau yra betoje, tai galit peržiūrėt ir pafeedbackint, kam įdomu @SnoutUp @PovilasLT ;)

**Comment by SnoutUp** [comment]
Kol kas matau tik šitą paveiksliuką :) (add issue: "Reikia geresnio maintenance puslapio") 

![image](https://cloud.githubusercontent.com/assets/5189737/12320040/ed59cae8-baae-11e5-9e76-1ce975dd8b59.png)

**Comment by SkepticalHippo** [comment]
Lyg turėtų dabar viskas gerai būti @SnoutUp

**Comment by SnoutUp** [comment]
Na, man dabar yra nuostabu, palyginus su tuo, kaip buvo anksčiau. Dar papildomos informacijos apie temos sukūrėją ir datą hoverinant temos pavadinimą arba ikoną trūksta.

Nenoriu kurt atskiro issue, bet gal nereikia šypsenėlių temos pavadinimuose? :) Dar to neteko matyt niekur :))
