### ISSUE TITLE
Panašios temos skydelis

### ISSUE THREAD

**Issue by Optimist78** [SkepticalHippo/maze#99]
Siūlau paredaguoti "Panašios temos" skyrelį, nežinau kaip jis veikia, tačiau tikrai, kad ne tinkamai, kuo panašios šios tema į tas tame skydelyje?

![image](https://cloud.githubusercontent.com/assets/16598956/12298375/b56a8ef6-ba09-11e5-9304-c86621ea034a.png)
![image](https://cloud.githubusercontent.com/assets/16598956/12298435/01a9e424-ba0a-11e5-906b-e0b819ff9833.png)

ir t.t.

**Comment by SkepticalHippo** [comment]
Panašios tuo, kad toje pačioje skiltyje. Kuo tikslesnė skiltis, e.g. ne "Apie Viską", tuo tikslesnės temos skydelyje.
